# O que o docker-compose.yml faz é simples de entnder
# Ele executa containers, permitindo uma maior facilidade
# Em executar containers que dependem de outros.

# Os containers são representados por serviços.

services:
  db:
    #Todo container precisa ter sua imagem explícita.
    image: mysql:latest
    container_name: mysqlFirstAttempt
    restart: always #Se der algum erro, sempre vai reiniciar
    environment: #variáveis de ambiente
      MYSQL_ROOT_PASSWORD: cayque123
      MYSQL_DATABASE: bdDoCayque
      MYSQL_USER: cayque
      MYSQL_PASSWORD: 123
    ports: # Vai ser compartilhado por diferentes serviços ao ser iniciado pelo docker-compose.
     - '3306:3306'


  phpMyAdming:
    image: phpmyadmin
    restart: always
    ports:
     - '8080:80'
     # php my admin depende do banco de dados, logo tem que deixar isso explicitado por um atributo
    depends_on:
     - db
    environment:
      PMA_HOST: db # Endereço ou nome do servidor MSQL
      MYSQL_ROOT_PASSWORD: cayque123

  # o caractere '-' indica que o item faz parte de uma lista
  # Colocar entre aspas simples indica que o valor de um atributo é uma string com certas propriedades especiais. Entretanto isso só é necessário em alguns casos, mas se você quiser separa todas as strings esteticamente, pode-se fazer uso disso.